[2023-04-14T22:16:55.084+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches.launch scheduled__2023-01-01T00:03:40+00:00 [queued]>
[2023-04-14T22:16:55.633+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches.launch scheduled__2023-01-01T00:03:40+00:00 [queued]>
[2023-04-14T22:16:55.642+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:16:55.651+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-14T22:16:55.693+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:16:56.048+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): launch> on 2023-01-01 00:03:40+00:00
[2023-04-14T22:16:56.087+0000] {standard_task_runner.py:55} INFO - Started process 532 to run task
[2023-04-14T22:16:56.151+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'launches', 'launch', 'scheduled__2023-01-01T00:03:40+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpa_r3ij28']
[2023-04-14T22:16:56.163+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask launch
[2023-04-14T22:17:00.579+0000] {task_command.py:389} INFO - Running <TaskInstance: launches.launch scheduled__2023-01-01T00:03:40+00:00 [running]> on host a0b8dfb9f67f
[2023-04-14T22:17:05.391+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Amogh Srigopal
AIRFLOW_CTX_DAG_ID=launches
AIRFLOW_CTX_TASK_ID=launch
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:03:40+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:03:40+00:00
[2023-04-14T22:17:05.400+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T22:17:05.405+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python launches.py']
[2023-04-14T22:17:05.507+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T22:17:06.368+0000] {subprocess.py:93} INFO - python: can't open file 'launches.py': [Errno 2] No such file or directory
[2023-04-14T22:17:06.424+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-14T22:17:06.465+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-14T22:17:06.511+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=launches, task_id=launch, execution_date=20230101T000340, start_date=20230414T221655, end_date=20230414T221706
[2023-04-14T22:17:06.688+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 61 for task launch (Bash command failed. The command returned a non-zero exit code 2.; 532)
[2023-04-14T22:17:06.879+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T22:17:07.113+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
