[2023-04-14T22:11:31.206+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: launches.launch scheduled__2023-01-01T00:04:00+00:00 [queued]>
[2023-04-14T22:11:31.237+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: launches.launch scheduled__2023-01-01T00:04:00+00:00 [queued]>
[2023-04-14T22:11:31.240+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:11:31.243+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-14T22:11:31.248+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-14T22:11:31.309+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): launch> on 2023-01-01 00:04:00+00:00
[2023-04-14T22:11:31.393+0000] {standard_task_runner.py:55} INFO - Started process 327 to run task
[2023-04-14T22:11:31.411+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'launches', 'launch', 'scheduled__2023-01-01T00:04:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpsfmf3ff0']
[2023-04-14T22:11:31.454+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask launch
[2023-04-14T22:11:31.790+0000] {task_command.py:389} INFO - Running <TaskInstance: launches.launch scheduled__2023-01-01T00:04:00+00:00 [running]> on host a0b8dfb9f67f
[2023-04-14T22:11:32.281+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Amogh Srigopal
AIRFLOW_CTX_DAG_ID=launches
AIRFLOW_CTX_TASK_ID=launch
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:04:00+00:00
[2023-04-14T22:11:32.285+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-14T22:11:32.288+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /Users/amoghsrigopal/Downloads/SpaceDataPipeline/launches.py']
[2023-04-14T22:11:32.331+0000] {subprocess.py:86} INFO - Output:
[2023-04-14T22:11:32.763+0000] {subprocess.py:93} INFO - python: can't open file '/Users/amoghsrigopal/Downloads/SpaceDataPipeline/launches.py': [Errno 2] No such file or directory
[2023-04-14T22:11:32.787+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-14T22:11:32.874+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-14T22:11:32.905+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=launches, task_id=launch, execution_date=20230101T000400, start_date=20230414T221131, end_date=20230414T221132
[2023-04-14T22:11:33.266+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task launch (Bash command failed. The command returned a non-zero exit code 2.; 327)
[2023-04-14T22:11:33.380+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-14T22:11:33.523+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
