[2023-04-16T02:18:55.574+0000] {processor.py:153} INFO - Started process (PID=251) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:18:55.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:18:55.582+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:18:55.582+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:18:55.634+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:18:55.627+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:18:55.641+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:18:55.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.122 seconds
[2023-04-16T02:19:26.386+0000] {processor.py:153} INFO - Started process (PID=276) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:26.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:19:26.407+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:19:26.406+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:26.489+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:19:26.474+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:19:26.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:26.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.348 seconds
[2023-04-16T02:19:57.581+0000] {processor.py:153} INFO - Started process (PID=303) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:57.597+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:19:57.614+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:19:57.614+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:57.675+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:19:57.667+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:19:57.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:19:57.787+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.211 seconds
[2023-04-16T02:20:29.147+0000] {processor.py:153} INFO - Started process (PID=332) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:29.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:20:29.166+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:20:29.165+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:29.216+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:20:29.209+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:20:29.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:29.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.182 seconds
[2023-04-16T02:20:59.375+0000] {processor.py:153} INFO - Started process (PID=359) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:59.378+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:20:59.383+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:20:59.382+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:59.416+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:20:59.411+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:20:59.421+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:20:59.525+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.161 seconds
[2023-04-16T02:21:30.203+0000] {processor.py:153} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:21:30.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:21:30.212+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:21:30.212+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:21:30.248+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:21:30.240+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:21:30.256+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:21:30.345+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.151 seconds
[2023-04-16T02:22:01.078+0000] {processor.py:153} INFO - Started process (PID=411) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:01.089+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:22:01.105+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:22:01.105+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:01.155+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:22:01.146+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:22:01.160+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:01.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.163 seconds
[2023-04-16T02:22:31.965+0000] {processor.py:153} INFO - Started process (PID=440) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:31.971+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:22:31.974+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:22:31.974+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:32.014+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:22:32.009+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:22:32.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:22:32.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.112 seconds
[2023-04-16T02:23:03.164+0000] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:03.174+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:23:03.188+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:23:03.188+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:03.274+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:23:03.244+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:23:03.277+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:03.394+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.253 seconds
[2023-04-16T02:23:34.102+0000] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:34.116+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:23:34.122+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:23:34.121+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:34.187+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:23:34.182+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:23:34.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:23:34.266+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.180 seconds
[2023-04-16T02:24:04.938+0000] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:04.943+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:24:04.948+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:24:04.948+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:04.981+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:24:04.976+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:24:04.984+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:05.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.113 seconds
[2023-04-16T02:24:35.868+0000] {processor.py:153} INFO - Started process (PID=550) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:35.874+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:24:35.878+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:24:35.877+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:35.913+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:24:35.907+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:24:35.917+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:24:35.961+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.103 seconds
[2023-04-16T02:25:06.541+0000] {processor.py:153} INFO - Started process (PID=577) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:06.545+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:25:06.548+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:25:06.548+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:06.570+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:25:06.566+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:25:06.574+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:06.610+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.075 seconds
[2023-04-16T02:25:37.358+0000] {processor.py:153} INFO - Started process (PID=604) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:37.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:25:37.368+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:25:37.368+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:37.393+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:25:37.389+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:25:37.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:25:37.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.091 seconds
[2023-04-16T02:26:07.990+0000] {processor.py:153} INFO - Started process (PID=629) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:07.995+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:26:08.000+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:26:07.999+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:08.043+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:26:08.035+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:26:08.046+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:08.112+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.132 seconds
[2023-04-16T02:26:38.994+0000] {processor.py:153} INFO - Started process (PID=666) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:38.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:26:39.004+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:26:39.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:39.030+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:26:39.026+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:26:39.034+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:26:39.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.095 seconds
[2023-04-16T02:27:09.646+0000] {processor.py:153} INFO - Started process (PID=693) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:09.655+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:27:09.659+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:27:09.658+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:09.686+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:27:09.682+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:27:09.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:09.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.103 seconds
[2023-04-16T02:27:40.626+0000] {processor.py:153} INFO - Started process (PID=719) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:40.631+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:27:40.638+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:27:40.638+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:40.678+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:27:40.673+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:27:40.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:27:40.743+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.127 seconds
[2023-04-16T02:28:11.451+0000] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:11.456+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:28:11.465+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:28:11.464+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:11.508+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:28:11.497+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:28:11.514+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:11.573+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.131 seconds
[2023-04-16T02:28:42.436+0000] {processor.py:153} INFO - Started process (PID=772) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:42.443+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:28:42.448+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:28:42.448+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:42.482+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:28:42.478+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:28:42.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:28:42.574+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.151 seconds
[2023-04-16T02:29:13.502+0000] {processor.py:153} INFO - Started process (PID=802) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:13.507+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:29:13.512+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:29:13.511+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:13.540+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:29:13.535+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:29:13.547+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:13.624+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.134 seconds
[2023-04-16T02:29:44.304+0000] {processor.py:153} INFO - Started process (PID=829) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:44.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:29:44.312+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:29:44.312+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:44.339+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:29:44.334+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:29:44.344+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:29:44.410+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.116 seconds
[2023-04-16T02:30:14.989+0000] {processor.py:153} INFO - Started process (PID=856) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:14.992+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:30:14.996+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:30:14.995+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:15.023+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:30:15.019+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:30:15.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:15.075+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.092 seconds
[2023-04-16T02:30:45.574+0000] {processor.py:153} INFO - Started process (PID=883) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:45.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:30:45.581+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:30:45.580+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:45.614+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:30:45.610+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:30:45.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:30:45.670+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.102 seconds
[2023-04-16T02:31:16.161+0000] {processor.py:153} INFO - Started process (PID=910) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:16.164+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:31:16.171+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:31:16.171+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:16.196+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:31:16.192+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:31:16.201+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:16.259+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.106 seconds
[2023-04-16T02:31:46.654+0000] {processor.py:153} INFO - Started process (PID=935) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:46.661+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:31:46.672+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:31:46.672+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:46.704+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:31:46.700+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:31:46.707+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:31:46.764+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.116 seconds
[2023-04-16T02:32:17.355+0000] {processor.py:153} INFO - Started process (PID=964) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:17.361+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:32:17.367+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:32:17.367+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:17.394+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:32:17.390+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:32:17.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:17.445+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.099 seconds
[2023-04-16T02:32:47.851+0000] {processor.py:153} INFO - Started process (PID=989) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:47.861+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:32:47.870+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:32:47.869+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:47.904+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:32:47.898+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:32:47.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:32:47.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.128 seconds
[2023-04-16T02:33:18.475+0000] {processor.py:153} INFO - Started process (PID=1017) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:18.480+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:33:18.483+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:33:18.482+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:18.523+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:33:18.518+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:33:18.526+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:18.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.126 seconds
[2023-04-16T02:33:49.215+0000] {processor.py:153} INFO - Started process (PID=1046) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:49.220+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:33:49.223+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:33:49.223+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:49.245+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:33:49.241+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:33:49.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:33:49.283+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.074 seconds
[2023-04-16T02:34:19.943+0000] {processor.py:153} INFO - Started process (PID=1074) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T02:34:19.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T02:34:19.949+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:34:19.949+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:34:19.973+0000] {logging_mixin.py:137} INFO - [2023-04-16T02:34:19.967+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T02:34:19.979+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T02:34:20.028+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.091 seconds
[2023-04-16T04:07:51.800+0000] {processor.py:153} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:07:51.806+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:07:51.810+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:07:51.809+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:07:51.857+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:07:51.852+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:07:51.860+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:07:51.994+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.200 seconds
[2023-04-16T04:08:23.128+0000] {processor.py:153} INFO - Started process (PID=203) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:23.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:08:23.136+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:08:23.135+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:23.169+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:08:23.164+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:08:23.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:23.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.169 seconds
[2023-04-16T04:08:53.892+0000] {processor.py:153} INFO - Started process (PID=229) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:53.906+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:08:53.909+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:08:53.908+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:53.947+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:08:53.942+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:08:53.951+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:08:54.005+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.133 seconds
[2023-04-16T04:09:24.533+0000] {processor.py:153} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:24.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:09:24.547+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:09:24.546+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:24.572+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:09:24.567+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:09:24.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:24.671+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.149 seconds
[2023-04-16T04:09:55.140+0000] {processor.py:153} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:55.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:09:55.156+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:09:55.156+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:55.203+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:09:55.193+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:09:55.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:09:55.272+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.144 seconds
[2023-04-16T04:10:25.716+0000] {processor.py:153} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:25.720+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:10:25.724+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:10:25.724+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:25.753+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:10:25.747+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:10:25.756+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:25.806+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.102 seconds
[2023-04-16T04:10:56.314+0000] {processor.py:153} INFO - Started process (PID=337) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:56.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:10:56.333+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:10:56.324+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:56.374+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:10:56.367+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:10:56.378+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:10:56.437+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.135 seconds
[2023-04-16T04:11:26.785+0000] {processor.py:153} INFO - Started process (PID=365) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:26.792+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:11:26.796+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:11:26.796+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:26.823+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:11:26.820+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:11:26.829+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:27.072+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.314 seconds
[2023-04-16T04:11:57.642+0000] {processor.py:153} INFO - Started process (PID=399) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:57.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:11:57.652+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:11:57.652+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:57.684+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:11:57.676+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:11:57.689+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:11:57.767+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.137 seconds
[2023-04-16T04:12:28.300+0000] {processor.py:153} INFO - Started process (PID=427) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:28.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:12:28.317+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:12:28.316+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:28.362+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:12:28.349+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:12:28.366+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:28.488+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.196 seconds
[2023-04-16T04:12:59.028+0000] {processor.py:153} INFO - Started process (PID=453) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:59.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:12:59.050+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:12:59.050+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:59.136+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:12:59.128+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:12:59.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:12:59.294+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.316 seconds
[2023-04-16T04:13:29.905+0000] {processor.py:153} INFO - Started process (PID=480) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:13:29.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:13:29.914+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:13:29.914+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:13:29.940+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:13:29.937+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:13:29.943+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:13:29.988+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.092 seconds
[2023-04-16T04:14:00.524+0000] {processor.py:153} INFO - Started process (PID=507) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:00.527+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:14:00.530+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:14:00.529+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:00.554+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:14:00.549+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:14:00.558+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:00.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.081 seconds
[2023-04-16T04:14:31.030+0000] {processor.py:153} INFO - Started process (PID=534) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:31.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:14:31.036+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:14:31.035+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:31.054+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:14:31.050+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:14:31.055+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:14:31.096+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.074 seconds
[2023-04-16T04:15:01.539+0000] {processor.py:153} INFO - Started process (PID=559) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:01.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:15:01.547+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:15:01.546+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:01.572+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:15:01.567+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:15:01.575+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:01.622+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.091 seconds
[2023-04-16T04:15:32.062+0000] {processor.py:153} INFO - Started process (PID=589) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:32.065+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:15:32.068+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:15:32.067+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:32.087+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:15:32.083+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:15:32.091+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:15:32.128+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.072 seconds
[2023-04-16T04:16:02.733+0000] {processor.py:153} INFO - Started process (PID=614) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:02.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:16:02.741+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:16:02.740+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:02.772+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:16:02.761+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:16:02.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:02.865+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.140 seconds
[2023-04-16T04:16:33.314+0000] {processor.py:153} INFO - Started process (PID=643) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:33.320+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:16:33.322+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:16:33.322+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:33.342+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:16:33.339+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:16:33.345+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:16:33.384+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.077 seconds
[2023-04-16T04:17:03.953+0000] {processor.py:153} INFO - Started process (PID=669) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:03.956+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:17:03.959+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:17:03.959+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:03.982+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:17:03.977+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:17:03.987+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:04.035+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.088 seconds
[2023-04-16T04:17:34.548+0000] {processor.py:153} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:34.551+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:17:34.554+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:17:34.554+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:34.575+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:17:34.571+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:17:34.578+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:17:34.617+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.076 seconds
[2023-04-16T04:18:05.306+0000] {processor.py:153} INFO - Started process (PID=722) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:05.309+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:18:05.312+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:18:05.311+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:05.333+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:18:05.329+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:18:05.335+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:05.373+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.073 seconds
[2023-04-16T04:18:35.830+0000] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:35.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:18:35.837+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:18:35.836+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:35.866+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:18:35.860+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:18:35.871+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:18:35.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.098 seconds
[2023-04-16T04:19:06.798+0000] {processor.py:153} INFO - Started process (PID=775) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:06.805+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:19:06.809+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:19:06.809+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:06.854+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:19:06.842+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:19:06.858+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:06.908+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.120 seconds
[2023-04-16T04:19:37.269+0000] {processor.py:153} INFO - Started process (PID=802) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:37.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:19:37.276+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:19:37.276+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:37.297+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:19:37.293+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:19:37.299+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:19:37.340+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.078 seconds
[2023-04-16T04:20:07.866+0000] {processor.py:153} INFO - Started process (PID=828) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:07.870+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:20:07.873+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:20:07.872+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:07.893+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:20:07.890+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:20:07.898+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:07.937+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.077 seconds
[2023-04-16T04:20:38.506+0000] {processor.py:153} INFO - Started process (PID=854) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:38.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:20:38.514+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:20:38.514+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:38.541+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:20:38.537+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:20:38.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:20:38.586+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.090 seconds
[2023-04-16T04:21:09.158+0000] {processor.py:153} INFO - Started process (PID=882) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:09.161+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:21:09.164+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:21:09.164+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:09.194+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:21:09.187+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:21:09.197+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:09.237+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.086 seconds
[2023-04-16T04:21:39.776+0000] {processor.py:153} INFO - Started process (PID=909) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:39.781+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:21:39.784+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:21:39.783+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:39.807+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:21:39.803+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:21:39.812+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:21:39.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.088 seconds
[2023-04-16T04:22:10.124+0000] {processor.py:153} INFO - Started process (PID=936) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:10.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:22:10.129+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:22:10.129+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:10.150+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:22:10.146+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:22:10.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:10.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.073 seconds
[2023-04-16T04:22:40.772+0000] {processor.py:153} INFO - Started process (PID=964) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:40.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:22:40.779+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:22:40.779+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:40.801+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:22:40.797+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:22:40.805+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:22:40.855+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.091 seconds
[2023-04-16T04:23:11.665+0000] {processor.py:153} INFO - Started process (PID=990) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:11.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:23:11.680+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:23:11.678+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:11.714+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:23:11.708+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:23:11.717+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:11.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.262 seconds
[2023-04-16T04:23:42.186+0000] {processor.py:153} INFO - Started process (PID=1017) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:42.190+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:23:42.193+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:23:42.193+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:42.246+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:23:42.229+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:23:42.254+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:23:42.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.141 seconds
[2023-04-16T04:24:12.654+0000] {processor.py:153} INFO - Started process (PID=1044) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:12.658+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:24:12.661+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:24:12.661+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:12.682+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:24:12.679+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:24:12.685+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:12.724+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.076 seconds
[2023-04-16T04:24:42.959+0000] {processor.py:153} INFO - Started process (PID=1071) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:42.963+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:24:42.967+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:24:42.967+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:43.001+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:24:42.993+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:24:43.005+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:24:43.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.107 seconds
[2023-04-16T04:25:13.999+0000] {processor.py:153} INFO - Started process (PID=1098) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:14.006+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:25:14.014+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:25:14.014+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:14.058+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:25:14.054+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:25:14.061+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:14.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.118 seconds
[2023-04-16T04:25:45.687+0000] {processor.py:153} INFO - Started process (PID=1126) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:45.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:25:45.727+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:25:45.727+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:45.815+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:25:45.790+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:25:45.822+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:25:45.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.228 seconds
[2023-04-16T04:26:16.800+0000] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:16.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:26:16.805+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:26:16.805+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:16.825+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:26:16.822+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:26:16.827+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:16.864+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.070 seconds
[2023-04-16T04:26:47.441+0000] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:47.451+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:26:47.457+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:26:47.455+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:47.487+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:26:47.484+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:26:47.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:26:47.535+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.103 seconds
[2023-04-16T04:27:18.366+0000] {processor.py:153} INFO - Started process (PID=1207) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:18.374+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:27:18.378+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:27:18.378+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:18.400+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:27:18.397+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:27:18.403+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:18.440+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.079 seconds
[2023-04-16T04:27:49.027+0000] {processor.py:153} INFO - Started process (PID=1234) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:49.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:27:49.036+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:27:49.036+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:49.074+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:27:49.066+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:27:49.086+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:27:49.160+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.142 seconds
[2023-04-16T04:28:19.825+0000] {processor.py:153} INFO - Started process (PID=1261) to work on /opt/airflow/dags/dag_launch.py
[2023-04-16T04:28:19.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dag_launch.py for tasks to queue
[2023-04-16T04:28:19.834+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:28:19.833+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:28:19.858+0000] {logging_mixin.py:137} INFO - [2023-04-16T04:28:19.854+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dag_launch.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_launch.py", line 4, in <module>
    from launches import extract_images, extract_launches
ModuleNotFoundError: No module named 'launches'
[2023-04-16T04:28:19.861+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_launch.py
[2023-04-16T04:28:19.896+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dag_launch.py took 0.083 seconds
